export class UserReg {
  businessUnitId: string;
  businessUnitName: string;
  colorCode: string;
  createdBy: string;
  createdByName: string;
  createdDateTime: string;
  designation: string;
  email: string;
  firstLogin: string;
  firstName: string;
  fullName: string;
  id: string;
  lastName: string;
  location: string;
  message: string;
  newPassword: string;
  panelMember: string;
  password: string;
  roleId: string;
  roleName: string;
  sex: string;
  skillSet: string;
  status: string;
  updatedBy: string;
  updatedByName: string;
  updatedDateTime: string;
  cpass: string;
  image: string;
  keyword: string;
  contactNumber: string;
  mainMenuDto: any[];
  mainMenus: string;
  subMenus: string;
  active: string;
  managerId: string;
  managerName:string;
}
